#!/usr/bin/env python3

import sys
import xml.etree.ElementTree as ET

def main():
    root = ET.fromstring(sys.stdin.read())
    rule = root.find("rule")
    for t in ("string", "label", "output"):
        for s in rule.findall(t):
            print(f"::set-output name={s.get('name')}::{s.get('value')}")

if __name__ == "__main__":
    main()
