---
name: Renovate

on:
  pull_request:
    paths:
      - "renovate.json"
      - ".github/workflows/renovate.yaml"
  workflow_dispatch:
  schedule:
    - cron: "42 11 * * 3"

concurrency:
  group: renovate

jobs:
  renovate:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.1.10
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: "debug"
          RENOVATE_BASE_BRANCH_PATTERNS: ${{ format('["{0}"]', github.head_ref || 'main') }}
          RENOVATE_DRY_RUN: ${{ github.event_name == 'pull_request' && 'full' || '' }}
          RENOVATE_GITHUB_COM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RENOVATE_REPOSITORIES: ${{ format('["{0}"]', github.repository) }}
          RENOVATE_USE_BASE_BRANCH_CONFIG: ${{ github.event_name == 'pull_request' && 'merge' || 'none' }}
